### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by jieyujing** [fejich/docker-embyhack#4]
输入任意密钥，只是保存成功，并没有激活，是哪里操作有问题么，还是最新版的emby不支持。

**Comment by fejich** [comment]
这个是服务器端的激活，保存后就可以启用硬件转码加速

想在客户端显示激活后的小金标，需要其他手段

**Comment by jieyujing** [comment]
好的，感谢回复

fejich ***@***.***> 于2023年3月22日周三 19:44写道：

**Comment by JellyZhang** [comment]
> 这个是服务器端的激活，保存后就可以启用硬件转码加速
> 
> 想在客户端显示激活后的小金标，需要其他手段

请问能使用电视直播功能么

**Comment by fejich** [comment]
> > 这个是服务器端的激活，保存后就可以启用硬件转码加速
> > 想在客户端显示激活后的小金标，需要其他手段
> 
> 请问能使用电视直播功能么

客户端显示小金标后，可以使用
