### ISSUE TITLE
这个方法还能用么？部署了4.7.11版本的emby没用？

### ISSUE THREAD

**Issue by zhouyunjian** [fejich/docker-embyhack#5]
![image](https://github.com/fejich/docker-embyhack/assets/16754064/88edcff0-a87d-4b36-bc5a-8054bef1ecb0)

输入密钥提示无效

**Comment by fejich** [comment]
检查

`embyhack/nginx/log/nginx/access.log`

正常情况下看到类似下边的内容

```
172.22.0.3 - - [20/Sep/2023:14:20:29 +0800] "POST /admin/service/registration/validate HTTP/1.1" 200 63 "-" "-"
```

刚刚测试了下，还能正常使用

**Comment by bgzo** [comment]
Sorry for bothering，I think I could give an advice: **NO PROXY**!

I edit this config and add the environment I used, so I check packets sending, it pass on my proxy server, not nginx server. So this is reason. 😂 

The normal screenshot is like this:

```
![Screenshot_20231014_203100](https://github.com/fejich/docker-embyhack/assets/57313137/2731f849-4644-4229-895d-ff46ac9d6a74)
```

Thank you for your work.
