### ISSUE TITLE
emby镜像可以使用官方的吗？

### ISSUE THREAD

**Issue by jackloves111** [fejich/docker-embyhack#6]
大佬用的是linuxserver/emby，官方我用的是emby/emby

**Comment by fejich** [comment]
注释掉第二行，应该就可以了
具体得自行测试下
```
    volumes:
      - ./ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt #将添加了 伪造CA证书 的信任列表，替换到容器内
#      - ./emby-ca-certificates.crt:/app/emby/etc/ssl/certs/ca-certificates.crt ##将添加了 伪造CA证书 的信任列表，替换到容器内（emby 的 c# 环境）
```

**Comment by pickarm** [comment]
> 注释掉第二行，应该就可以了 具体得自行测试下
> 
> ```
>     volumes:
>       - ./ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt #将添加了 伪造CA证书 的信任列表，替换到容器内
> #      - ./emby-ca-certificates.crt:/app/emby/etc/ssl/certs/ca-certificates.crt ##将添加了 伪造CA证书 的信任列表，替换到容器内（emby 的 c# 环境）
> ```

![image](https://github.com/user-attachments/assets/2e248d0a-802e-411e-824e-7cdd792f0649)
我是在emby端加了这两个路径，伪站是我用远端搭建的，本地做了dns劫持，官方docker这边不生效

**Comment by fejich** [comment]
看了下，官方 emby/embyserver 这个镜像基于
`BusyBox 1.37.0 (musl), Alpine 3.20.3`

替换 `ca-certificates.crt` 添加自签证书的方法无效
